//Generating console window
#include<graphics.h>

int main(){

    int gd = DETECT , gm ; //gd: Graphic Detect And DETECT is used to detec graphic driver and the value will be assigned to gd
    //gm: Graphics Mode
//Graphics window: Three Argument:
//1. int pointer to variable:Graphics driver
//2. int pointer to variable: address of gm
//3. path to the driver (we don't need to provide here) but it is like this: C:\\TC\\BGI 
    initgraph(&gd, &gm, (char*)"");

    getch();  //To hold the output in string until any key is pressed
    closegraph();  //close the graphic window

    return 0;

}

/* Graphic window will be generated by running this code or console winodw in graphic mode
Top left part: origin
The window is 2D plane with y-axis inverted

*/